import { chromium } from '@playwright/test';
const b = await chromium.launch();
const ctx = await b.newContext({ viewport:{width:1600,height:1000} });
await ctx.addInitScript(()=>{ try{ localStorage.setItem('foldo:cookie-acked','1'); localStorage.setItem('foldo:demoUserId','u-you'); localStorage.setItem('foldo:firstRunHintDismissed','1'); }catch{} });
const p = await ctx.newPage();
await p.goto('http://localhost:5273/board/board-acme-landing',{waitUntil:'domcontentloaded',timeout:30000});
await p.locator('[data-frame-kind="app"]').first().waitFor({state:'visible',timeout:20000});
await p.waitForTimeout(3000);
await p.screenshot({ path:'/tmp/foldo-e2e/xt/bottom-strip.png', clip:{x:0,y:880,width:1600,height:120} });
await b.close(); console.log('ok');
