import { chromium } from '@playwright/test';
const b=await chromium.launch();
const ctx=await b.newContext({viewport:{width:1600,height:200}});
await ctx.addInitScript(()=>{try{localStorage.setItem('foldo:cookie-acked','1');localStorage.setItem('foldo:demoUserId','u-you');}catch{}});
const p=await ctx.newPage();
await p.goto('http://localhost:5273/board/board-acme-landing',{waitUntil:'domcontentloaded',timeout:30000});
await p.waitForTimeout(3500);
await p.screenshot({path:'/tmp/foldo-e2e/xt/topbar-left.png',clip:{x:0,y:0,width:430,height:60}});
await p.screenshot({path:'/tmp/foldo-e2e/xt/topbar-right.png',clip:{x:1060,y:0,width:540,height:60}});
await b.close();console.log('ok');
