import { chromium } from '@playwright/test';
const ctx = await chromium.launchPersistentContext('/Users/lukadadiani/Documents/Client/.xt-session', { headless:true, viewport:{width:1440,height:900}, args:['--no-first-run'] });
const p = ctx.pages()[0] ?? await ctx.newPage();
await p.goto('http://localhost:8000', { waitUntil:'networkidle', timeout:30000 }).catch(()=>{});
await p.waitForTimeout(7000);
const url = p.url();
const onB2C = /b2clogin\.com|login\.microsoftonline/.test(url);
const authBtn = await p.locator('button:has-text("Authenticate")').count();
const text = (await p.locator('body').innerText().catch(()=> '')).replace(/\s+/g,' ').slice(0,220);
const localKeys = await p.evaluate(() => Object.keys(localStorage).filter(k=>/msal|account|token|login|idtoken/i.test(k)).slice(0,10));
await p.screenshot({ path:'/tmp/foldo-e2e/xt/verify.png' });
console.log(JSON.stringify({ url, onB2C, authBtn, msalKeyCount: localKeys.length, text }, null, 2));
await ctx.close();
